### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by ghost** [KillerBOSS2019/TP-Speed-Test-Plugin#5]
Hi 
The button visual is empty,

I measure the error below 

Log with command TPSpeedtest.exe -d -l log.txt
`C:\Users\Samuel\AppData\Roaming\TouchPortal\plugins\TPSpeedTest>TPSpeedtest.exe -d -l log.txt
Namespace(d=True, w=False, q=False, l='log.txt', s='stdout')
130 INFO: Starting SpeedTest v2001 on win32.
17:26:04.241 [I] [main.py:259] Starting SpeedTest v2001 on win32.
2167 ERROR: Exception in TP Client:
Traceback (most recent call last):
  File "main.py", line 262, in main
  File "TouchPortalAPI\client.py", line 617, in connect
  File "TouchPortalAPI\client.py", line 288, in __open
ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

17:26:06.278 [E] [main.py:268] Exception in TP Client:
Traceback (most recent call last):
  File "main.py", line 262, in main
  File "TouchPortalAPI\client.py", line 617, in connect
  File "TouchPortalAPI\client.py", line 288, in __open
ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

2169 INFO: SpeedTest stopped.
17:26:06.280 [I] [main.py:276] SpeedTest stopped.

C:\Users\Samuel\AppData\Roaming\TouchPortal\plugins\TPSpeedTest>`

**Comment by ghost** [comment]
UP please
